apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mqg-ns
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer1
  name: consumer1
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: consumer1
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer1
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: consumer
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq-default-user

          image: chaitanyawho/rmq-tutorial/consumer:1.1.0
          name: consumer1
          resources: { }
      restartPolicy: Always
status: { }
